language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - docker
#install dependencies
install:
  - pip install -r requirements.txt
#command to run the testing
script:
  - scripts/pipeline_test.py
